---
- hosts: all
  sudo_user: root
  vars_files:
    - 'defaults/postgresql.yml'
    - 'defaults/zabbix.yml'
    - 'defaults/httpd.yml'
  tasks:
    - include: 'tasks/main.yml'
  handlers:
    - include: 'handlers/main.yml'
  #vars_prompt:
    #ip_httpd: "On what IP should apache run? "
#    install_method: "Do you want to install from online or offline sources (online/offline) ?"
